# config/actions.py - to validate output schemas without spending LLM tokens
import json
from nemoguardrails.actions import action

@action(name="validate_json_action")
async def validate_json_action(output: str) -> bool:
    """
    Checks if the output generated by Gemini is valid JSON.
    Runs locally in Python without an LLM call.
    """
    if not output:
        return False
    try:
        # Clean markdown code blocks if Gemini wraps it in ```json ... ```
        cleaned_output = output.strip()
        if cleaned_output.startswith("```json"):
            cleaned_output = cleaned_output[7:]
        if cleaned_output.startswith("```"):
            cleaned_output = cleaned_output[3:]
        if cleaned_output.endswith("```"):
            cleaned_output = cleaned_output[:-3]
        
        json.loads(cleaned_output.strip())
        return True
    except (json.JSONDecodeError, ValueError):
        return False