colang_version: "1.0"

models:
  - type: main
    engine: openai
    model: gateway-model
    parameters:
      base_url: "http://localhost:4000/v1"

rails:
  input:
    flows:
      - handle greeting
      - check input patterns
      - check pii and mask
      - check llama guard input

# Completely disables canonical LLM intent generation
dialog:
  user_intent: false

instructions:
  - type: general
    content: ""

sample_conversation: ""


# colang_version: "1.0"

# models:
#   - type: main
#     engine: openai
#     model: gateway-model
#     parameters:
#       base_url: "http://localhost:4000/v1"

#   - type: embeddings
#     engine: openai
#     model: text-embedding-3-small
#     parameters:
#       base_url: "http://localhost:4000/v1"

# rails:
#   input:
#     flows:
#       - check llama guard input

# dialog:
#   user_intent: false
